### PR TITLE
fixed issue 149

### PR DESCRIPTION
**Pull request by OkieOth**
I fixed the issue that for enums with struct values, attribs were not serialized. 

Since the change was a small one and I am not fully understand the impact, I added some tests too.

### CODE REVIEW

**Comment by MarcAntoine-Arnaud** [comment]
Hi @OkieOth 
It breaks the `ser_list_of_items` unit test. I think the bool update is not enough.

**Comment by OkieOth** [comment]
@MarcAntoine-Arnaud didn't recognize that. Are all tests on master running meanwhile? Then I will take an additional look.

**Comment by OkieOth** [comment]
Test on master are working also in my fork ... so i will debug what breaks. Thank you, for the info

**Comment by OkieOth** [comment]
Fixing this, in respect of the existing code is beyond my abilities. I couldn't find a way distinguish between the enum and the struct situation. I thought about introducing a new 'YaSerdeAttribute' but this looked too harsh, to me. 
As result I skip my doing and close the PR. Sorry for the noise :D

**Pull request closed without merging**
