### PR TITLE
Rename vector fields in struct

### PR DESCRIPTION
**Pull request by horacimacias**

### CODE REVIEW

**Comment by MarcAntoine-Arnaud** [comment]
looks cool, but fix the format, use 2 space indentation please.

**Comment by horacimacias** [comment]
ah sorry, let me try fixing that.

**Comment by MarcAntoine-Arnaud** [comment]
Can you add a unit test to support `flatten` on this kind of field ?
I think the current code has to be updated to support that.

**Comment by horacimacias** [comment]
sorry, can you please provide an example?
I'm not sure I see why you'd configure something to be renamed and flattened at the same time.
Wouldn't you be defining a specific name to be renamed to but at the same time asking for serialization to ignore the renaming by flattening the field?

**Comment by horacimacias** [comment]
let's see if the updates are what you meant. I've added some tests for non-flattened and flattened field.

**Comment by MarcAntoine-Arnaud** [comment]
Sorry I haven't time before your developments.
But yes basically in XML, an element can be present many times so it's for that the default usage of `Vec<items>` was made for that.
So your code look good regarding unit tests to extend `Vec` usage.

Can you also support both way, in the patch you have developed only for `serialize_and_validate` can you update for `deserialize` too ?

Thank you for your time on that ! Very helpfull contribution :D

**Comment by horacimacias** [comment]
thanks; sorry I was offline for some time

**Pull request merged**
