### PR TITLE
[WIP] Implement support for strict deserialization in structs.

### PR DESCRIPTION
**Pull request by definitelynobody**
Support can be enable like this:

```rust
#[derive(YaDeserialize, PartialEq, Debug)]
#[yaserde(strict, root = "root")]
pub struct XmlStruct {
  expected_tag: String,
}
```

Enabling this will cause errors when:

- [x] The root tag has an unexpected name
- [x] Any unexpected tag appears in the xml
- [x] Any unexpected attribute appears in the xml
- [ ] An expected tag is missing in the xml (ignore default)
- [ ] An expected attribute is missing in the xml (ignore default)

### CODE REVIEW

**Comment by MarcAntoine-Arnaud** [comment]
Thank you @definitelynobody !
I'll take a look on it this week. It's sounds good.
Is it possible for you to check bugs in CI ([on travis platform](https://travis-ci.org/media-io/yaserde/builds/558658562))?

- It can be great to add Rust version from 1.32 to 1.36
- maybe remove old version as it can be complex to support them

**Comment by MarcAntoine-Arnaud** [comment]
> Thank you @definitelynobody !
> I'll take a look on it this week. It's sounds good.
> Is it possible for you to check bugs in CI ([on travis platform](https://travis-ci.org/media-io/yaserde/builds/558658562))?
> 
> * It can be great to add Rust version from 1.32 to 1.36
> * maybe remove old version as it can be complex to support them

I have updated Rust versions on master branch. You can try to rebase to upgrade ;-)

**Comment by definitelynobody** [comment]
I'm having some issues with determining what attributes an XML should be inside of a struct and checking if they were found. This is mostly because i don't know when a tag is actually a root tag or another field struct inside of the main struct.

I will upload some failing tests this weekend to a branch to demonstrate.

**Comment by MarcAntoine-Arnaud** [comment]
I'll close the issue as no update is provided.
Some features are now supported in the library thanks to contributors.

**Pull request closed without merging**
